system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: False
  amp_level: 'O0'
  seed: 42
  log_interval: 10
  val_while_train: True
  drop_overflow_update: False

model:
  type: det
  transform: null
  backbone:
    name: det_resnet50
    pretrained: True
  neck:
    name: EASTFPN
    out_channels: 128
  head:
    name: EASTHead

postprocess:
  name: EASTPostprocess
  score_thresh: 0.8
  nms_thresh: 0.2

metric:
  name: DetMetric
  main_indicator: f-score

loss:
  name: EastLoss

scheduler:
  scheduler: 'cosine_decay'
  lr: 0.001
  min_lr: 0.00001
  num_epochs: 1200
  warmup_epochs: 10
  decay_epochs: 1150


optimizer:
  opt: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1.0e-4

# only used for mixed precision training
loss_scaler:
  type: dynamic
  loss_scale: 512
  scale_factor: 2
  scale_window: 1000

train:
  ckpt_save_dir: './train5'
  dataset_sink_mode: True
  dataset:
    type: DetDataset
    dataset_root: /home/tongli/data/icdar2015/
    data_dir: ch4_training_images
    label_file: train_det_gt.txt
    sample_ratio: 1.0
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - DetLabelEncode:
      - EASTProcessTrain:
          scale: 0.25
          length: 512
#      - RandomColorAdjust:
#          brightness: 0.1255  # 32.0 / 255
#          saturation: 0.5
#      - IaaAugment:
#          Fliplr: { p: 0.5 }
#          Affine: { rotate: [ -10, 10 ] }
#      - RandomScale:
#          scale_range: [ 0.5, 3.0 ]
#      - RandomCropWithBBox:
#          max_tries: 10
#          min_crop_ratio: 0.1
#          crop_size: [ 640, 640 ]
#      - ShrinkBinaryMap:
#          min_text_size: 8
#          shrink_ratio: 0.4
#      - BorderMap:
#          shrink_ratio: 0.4
#          thresh_min: 0.3
#          thresh_max: 0.7
#      - NormalizeImage:
#          bgr_to_rgb: False
#          is_hwc: True
#          mean: imagenet
#          std: imagenet
#      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visualize
    output_columns: ['image', 'score_map', 'geo_map', 'training_mask']
#    output_columns: ['image'] # for debug op performance
    num_columns_to_net: 1 # num inputs for network forward func in output_columns

  loader:
    shuffle: True
    batch_size: 20
    drop_remainder: True
    num_workers: 8

eval:
  ckpt_load_path: 'train5/best.ckpt'
  dataset_sink_mode: False
  dataset:
    type: DetDataset
    dataset_root: /home/tongli/data/icdar2015/
    data_dir: ch4_test_images
    label_file: test_det_gt.txt
    sample_ratio: 1.0
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - DetLabelEncode:
#      - GridResize:
#          factor: 32
      # GridResize already sets the evaluation size to [ 736, 1280 ].
      # Uncomment ScalePadImage block for other resolutions.
#      - ScalePadImage:
#          target_size: [ 736, 1280 ] # h, w
#      - NormalizeImage:
#          bgr_to_rgb: False
#          is_hwc: True
#          mean: imagenet
#          std: imagenet
#      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the labels for evaluation
    output_columns: [ 'image', 'polys', 'ignore_tags' ]
    num_columns_to_net: 1 # num inputs for network forward func
#    num_keys_of_labels: 2 # num labels

  loader:
    shuffle: False
    batch_size: 1 # TODO: due to dynamic shape of polygons (num of boxes varies), BS has to be 1
    drop_remainder: False
    num_workers: 1
