system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: False
  amp_level: 'O0'
  seed: 42
  log_interval: 100
  val_while_train: True
  drop_overflow_update: False

common:
  character_dict_path: &character_dict_path /home/tongli/workspace/mindocr_robustscanner_dev_new/mindocr/utils/dict/en_dict.txt
  num_classes: &num_classes 37 # num_chars_in_dict+1,  TODO: retreive it from dict or check correctness
  max_text_len: &max_text_len 40
  infer_mode: &infer_mode False
  use_space_char: &use_space_char False
  batch_size: &batch_size 128

#model:
#  type: rec
#  transform: null
#  backbone:
#    name: rec_resnet34
#    pretrained: False
#  neck:
#    name: RNNEncoder
#    hidden_size: 256
#  head:
#    name: CTCHead
#    weight_init: crnn_customised
#    bias_init: crnn_customised
#    out_channels: *num_classes

model:
  type: rec
  transform: null
  backbone:
    name: ResNet31
#    pretrained: False
  head:
    name: RobustScannerHead
    out_channels: 39  # 94 + unknown + start + padding ? 100
#    in_channels: 512
    enc_outchannles: 128
    hybrid_dec_rnn_layers: 2
    hybrid_dec_dropout: 0.
    position_dec_rnn_layers: 2
    start_idx: 37  # 91
    mask: True
    padding_idx: 38  # 92
    encode_value: False
    max_text_len: *max_text_len

postprocess:
  name: SARLabelDecode

metric:
  name: RecMetric
  main_indicator: acc
  character_dict_path: *character_dict_path
  ignore_space: True
  print_flag: False

loss:
  name: SARLoss

scheduler:
  scheduler: multi_step_decay
  milestones: [3, 4]
  decay_rate: 0.1
  lr: 0.001
  num_epochs: 5
  warmup_epochs: 0

optimizer:
  opt: adamW
  beta1: 0.9
  beta2: 0.999
  #use_nesterov: True

loss_scaler:
  type: static
  loss_scale: 512

train:
  ckpt_save_dir: './robustscanner_exp/robustscanner_8p_O0_graph_try6'
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    dataset_root: /home/tongli/data/lmdb/data_lmdb_release/ # Optional, if set, dataset_root will be used as a prefix for data_dir
    data_dir: training/
    # label_files: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: True
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - SARLabelEncode: # Class handling label
          max_text_len: *max_text_len
      - RobustScannerRecResizeImg:
          image_shape: [ 3, 48, 48, 160 ] # h:48 w:[48,160]
          width_downsample_ratio: 0.25
          max_text_len: *max_text_len
#      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
#          bgr_to_rgb: True
#          is_hwc: True
#          mean : [127.0, 127.0, 127.0]
#          std : [127.0, 127.0, 127.0]
#      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'label', 'valid_width_mask', 'word_positions']
    net_input_column_index: [0, 1, 2, 3] # input indices for network forward func in output_columns
    label_column_index: [0, 1, 2, 3] # input indices marked as label
    #keys_for_loss: 4 # num labels for loss func

  loader:
      shuffle: True # TODO: tbc
      batch_size: *batch_size
      drop_remainder: True
      max_rowsize: 12
      num_workers: 8

eval:
  ckpt_load_path: '/home/tongli/workspace/mindocr_robustscanner_dev_new/robustscanner_exp/robustscanner_8p_O0_graph_try6/best.ckpt'
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    dataset_root: /home/tongli/data/lmdb/data_lmdb_release/
    data_dir: evaluation_paddle/
    # label_files: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - SARLabelEncode: # Class handling label
          max_text_len: *max_text_len
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
#      - RecCTCLabelEncode:
#          max_text_len: *max_text_len
#          character_dict_path: *character_dict_path
#          use_space_char: *use_space_char
#          lower: True
      - RobustScannerRecResizeImg:
          image_shape: [ 3, 48, 48, 160 ]
          width_downsample_ratio: 0.25
          max_text_len: *max_text_len
#      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
#          bgr_to_rgb: True
#          is_hwc: True
#          mean : [127.0, 127.0, 127.0]
#          std : [127.0, 127.0, 127.0]
#      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: [ 'image', 'label', 'valid_width_mask', 'word_positions', 'text_padded', 'text_length' ]
    net_input_column_index: [ 0, 1, 2, 3 ] # input indices for network forward func in output_columns
    label_column_index: [4, 5]

  loader:
      shuffle: False # TODO: tbc
      batch_size: 1
      drop_remainder: True
      max_rowsize: 12
      num_workers: 8
